---
version: 0.2

phases:
  pre_build:
    commands:
      #- echo Logging in to Amazon ECR...
      #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- echo docker login successful.
      - IMAGE_NAME=fake-trades-api
      - cd faketrades-api
      - mvn clean package
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t fake-trades-api .
      - docker tag fake-trades-api:latest 964183462461.dkr.ecr.us-east-2.amazonaws.com/faketrades:fake-trades-api
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG